---
- name: Apt Update
  become: true
  ansible.builtin.apt:
    update-cache: true

- name: Apt Upgrade
  become: true
  ansible.builtin.apt:
    upgrade: full

- name: Install 
  apt:
    state: present
    name:
      - python3-pip
      - build-essential
      - git
      - acl
      - python3-psycopg2

- name: Upgrade pip
  pip: 
    name: pip 
    state: latest
