---
- name: Install PostgreSQL
  apt:
    pkg:
      - postgresql
    state: latest

- name: Start and enable postgres
  service: 
    name: postgresql
    enabled: yes
    state: started

- name: Create database
  postgresql_db: name={{ db_name }}
  become_user: postgres
  become: yes

- name: Create user
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres 
